default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  #adapter: sqlite3
  #database: db/development.sqlite3
  database: mushi

test:
  <<: *default
  #adapter: sqlite3
  #database: db/test.sqlite3
  database: mushi_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
