default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mushi

test:
  <<: *default
  database: mushi_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
